export const NAV_ITEMS = ["HOME","ABOUT","PORTFOLIO","BLOG","CONTACT"];
export const BRAND = "portfolio";
export const PROFILE_NAME = "Mohammed Anas M";
export const JOB_NAME = "Front-End Developer";
export const INTRO_PARA = "I am an experienced front-end developer with over 8.5 years in IT, specializing in web application development. My passion for coding is evident in the joy I find in this work, which I consider more than just a profession—it's a hobby. Throughout my career, I have adeptly navigated both front-end and back-end technologies, including Java Spring Boot, React JS, NextJS, React JS with TypeScript, SCSS, CSS, HTML, jQuery, React Query, Redux, Selenium with Java, and SikuliX with Python. My expertise extends to web development and robotic process automation. Currently, I am dedicated to web development using NextJS and React JS.";
export const FROM_PLACE = "Kerala";
export const LIVING_PLACE = "Bengaluru";
export const AGE = 28;
export const GENDER = "Male";
